# Generated by Django 6.0.2 on 2026-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('checked_in', 'Checked In'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('token_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
    ]
